[package]
name = "basics"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "authentication",
    "concurrency/divide_work",
    "concurrency/hello",
    "concurrency/scoped_threads",
    "concurrency/thread_builder",
    "console",
    "login",
    "login_manager",
]

[dependencies]
console = { path = "./console" }
