[package]
name = "basics"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "authentication",
    "concurrency/atomics",
    "concurrency/channels1",
    "concurrency/dashing",
    "concurrency/divide_work",
    "concurrency/footgun",
    "concurrency/hello",
    "concurrency/mutexes",
    "concurrency/parking",
    "concurrency/rwlocks",
    "concurrency/scoped_threads",
    "concurrency/thread_builder",
    "concurrency/thread_pool",
    "concurrency/workers",
    "console",
    "login",
    "login_manager",
]

[dependencies]
console = { path = "./console" }
