[package]
name = "shared_data"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bincode = { version = "1.3.3", features = ["i128"] }
crc32fast = "1.5.0"
serde = { version = "1.0.228", features = ["derive"] }
